dotnet/scenario-tests

src/Directory.Build.props

Avoid creating test packages that can't be executed.

Pack tests as tools

---

src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/Microsoft.DotNet.ScenarioTests.SdkTemplateTests.csproj

This allows the project to dynamically target the current TFM defined by Arcade. This is useful in source build right now since the VMR is overriding `NetCurrent` to be `net9.0`.

Use NetCurrent property

---

src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotNetSdkHelper.cs

`DotNetSdkHelper` is writing directly to the console for various messages. This produces unnecessary noise in the console when running the tool and is not captured in the log. It should be writing to `OutputHelper` instead.

Use OutputHelper instead of Console

---

src/Microsoft.DotNet.ScenarioTests.Common/Program.cs

The output file is in the format of [xUnit v1 XML schema](https://xunit.net/docs/format-xml-v1). This format is unsupported by Azure DevOps in order to view the results in the integrated Test view. As documented in the [`PublishTestResults` task](https://learn.microsoft.com/azure/devops/pipelines/tasks/reference/publish-test-results-v2), only the [v2 schema](https://xunit.net/docs/format-xml-v2) is supported.
In order to have support in Azure DevOps for the output produced by the scenario tests, these changes update the format to the v2 schema.

Use v2 format of xunit

---

src/Directory.Build.targets

This is related to the work for https://github.com/dotnet/installer/pull/19222. It updates the existing `Test` target to include more functionality so that this logic doesn't need to be defined outside by the VMR.

Update Test target

---

src/Directory.Build.targets

When calling the `Test` target, the `NETCoreSdkVersion` property is used to configure the test environment. In some cases, it's not possible for the caller to override that value because it is hardcoded by https://github.com/dotnet/installer/blob/bf738fd99f28f1d6b80cc6af97253dc7acf00a46/src/redist/targets/GenerateBundledVersions.targets#L534. This can prevent the tests from working in the VMR environment.
This is resolved by introducing a new overridable property, `TestSdkVersion`, that will default to `NETCoreSdkVersion` if not overridden.

Ensure SDK version can be overridden

---

src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTests.cs

WPF test isn't reliable for VMR execution: https://github.com/dotnet/source-build/issues/4361

Disable WPF template test

---

azure-pipelines.yml

We don't need any of the post-build validation steps for scenario-tests. As those are failing the build since a few months, disable them.

Disable validation stage in official builds

---

src/Microsoft.DotNet.ScenarioTests.Common/Program.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotNetSdkActions.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotNetSdkHelper.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTest.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTests.cs

Contributes to https://github.com/dotnet/source-build/issues/1215.
cc @MichaelSimons @jkotas @omajid

Add test for source-built bundled NativeAOT.

---

src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotnetWorkloadTest.cs

Reverts dotnet/scenario-tests#114
https://github.com/dotnet/sdk/pull/43797 is merged so we can re-enable the uninstall which might help with https://github.com/dotnet/source-build/issues/4636

Revert "Disabling workload uninstall test to enable -rtm branded sdk"

---

src/Microsoft.DotNet.ScenarioTests.Common/Program.cs
src/Microsoft.DotNet.ScenarioTests.Common/ScenarioTestFixture.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotnetWorkloadTest.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTest.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTests.cs

For community architectures, only non-portable assets are available.
@ViktorHofer @MichaelSimons ptal.
cc @omajid @Swapnali911

Skip tests that require portable assets on community architectures.

---

src/Microsoft.DotNet.ScenarioTests.Common/Program.cs
src/Microsoft.DotNet.ScenarioTests.Common/ScenarioTestFixture.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotNetSdkActions.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotNetSdkHelper.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotnetWorkloadTest.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTest.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTests.cs

Backports:
- https://github.com/dotnet/scenario-tests/pull/108
- https://github.com/dotnet/scenario-tests/pull/113
@mthalman ptal.

Backport #113 (NativeAOT test) and #108 (Skip on community architectures) to release/9.0.

---

src/Directory.Build.props

Allows re-enabling the scenario-tests in the VMR without re-targeting the tests to net10.0. Needed for https://github.com/dotnet/sdk/pull/44937

Add roll forward switch to scenario-tests

---

src/Microsoft.DotNet.ScenarioTests.Common/ExecuteHelper.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTest.cs

Fixes https://github.com/dotnet/scenario-tests/issues/96
I tested this locally by stepping through the tests and opening the port in the generated project's launchSettings.json and observing that it correctly does the retry and generates a new project with a new port.

Retry AddressInUseException during web scenarios

---

src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotNetSdkHelper.cs

While looking at https://github.com/dotnet/source-build/issues/4775 I noticed that we were leaving behind a lot of processes related to the web tests. This is because we were only killing the "dotnet run" process but that didn't terminate the child process with the actual web app.

Terminate child processes in ExecuteRunWeb too

---

azure-pipelines-pr-ci.yml

Adding a PR/CI yaml file. The current azure-pipelines.yml will be altered to be the official build after each in-service branch has this file.

Add a PR/CI yaml file

---

src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotNetSdkHelper.cs

When running the [Native AOT publish test](https://github.com/dotnet/scenario-tests/blob/338a5ed76d040627c6de30bf877c071ca303c193/src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTests.cs#L225), it doesn't end up setting the RID when calling `dotnet publish`. This leads to the issue described in https://github.com/dotnet/sdk/pull/46215#issuecomment-2610293316.
This updates the test infrastructure to set the RID on the `dotnet publish` command when it is provided, so by default it will include it for the Native AOT test.
cc @tmds

Ensure RID option is set for AOT publish scenario

---

src/Microsoft.DotNet.ScenarioTests.Common/Program.cs
src/Microsoft.DotNet.ScenarioTests.Common/ScenarioTestFixture.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotnetWorkloadTest.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTest.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTests.cs

Fixes https://github.com/dotnet/scenario-tests/issues/187
Partially unblocks https://github.com/dotnet/sdk/pull/46244
We will need to update this line in the VMR to pass the portableRid in: https://github.com/dotnet/sdk/blob/5aa4f469217ad30fa471dd36dd717fb305fb2084/src/SourceBuild/content/repo-projects/scenario-tests.proj#L39

Respect portable RID passed in via CLI or env var

---

src/Directory.Build.targets
src/Microsoft.DotNet.ScenarioTests.Common/Program.cs
src/Microsoft.DotNet.ScenarioTests.Common/ScenarioTestFixture.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotNetSdkHelper.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTests.cs

Contributes to https://github.com/dotnet/source-build/issues/4849
This needs a reaction in the VMR orchestrator post merge.

Add binlog switch that allows to put binlogs into a specific folder

---

src/Directory.Build.targets

Allow executing the test host with a specific shared framework version (i.e. 10.0.0-ci). This is necessary as i.e. in the VMR, the live built shared framework has a `-dev` or `-ci` suffix which could be determined as "lower" than the toolset SDK's shared framework that the repo builds with. As an example `10.0.0-ci` and `10.0.0-dev` are considered lower than `10.0.0-preview.1` by the host (in accordance with semver2).
Unblocks https://github.com/dotnet/sdk/pull/46558 (requires one update)

Support executing the test host with a specific --fx-version and define a default

---

azure-pipelines-pr-ci.yml
azure-pipelines.yml
eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml

Drop support for building source build prebuilt clean within the repo.  The reason this is being dropped is described in [Repository and VMR PR/CI validation Strategy](https://github.com/dotnet/arcade/blob/main/Documentation/UnifiedBuild/VMR-Repo-and-VMR-Validation.md)
1. Remove the source build legs from pr/ci
2. Remove the intermediate dependencies from Version.Details.xml
3. Remove the SourceBuildPrebuiltBaseline.xml file
I will remove the darc subscriptions for SBE and SBRP after merging this PR.

Drop support for prebuilt free local source-build

---

src/Directory.Build.targets
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotNetSdkHelper.cs

Fixes https://github.com/dotnet/source-build/issues/4489
Helps with https://github.com/dotnet/sdk/pull/46558

Simplify test setup in scenario-tests and allow setting a TestRestoreConfigFile and TestDotNetRoot

---

src/Microsoft.DotNet.ScenarioTests.Common/Program.cs
src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotNetSdkHelper.cs

MSBuild Exec's task invocation flows a few env vars down that cause issues when running scenario-test swith a live built SDK. I.e. the `MSBuildSDKsPath` env var which would point to the old SDK.
Ignore those env vars and also log the RestoreConfigFile env var if it is set.

Fix scenario-tests invocation in the VMR with a live built SDK

---

src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTests.cs

This allows disabling tests that only work after the full join in the VMR, e.g. windows-x64 publishing for browser-wasm

Add RequiresNonTargetRidPackages trait category
